### ISSUE TITLE
Optional field

### ISSUE THREAD

**Issue by alorma** [afollestad/vvalidator#1]
*Please consider making a Pull Request if you are capable of doing so.*

**Description what you'd like to happen:**

Imagine the following form:

```kotlin
form {
  input(R.id.input_site, name = "Site") {
     ...
  }
  
  input(R.id.input_age, name = "Age") {
      ...
  }
}
```

Would be great that "Age" is optional, so:

if user has introduced something, then validate it, otherwise not validate it among other fields.

**Describe alternatives you've considered:**

I see some options to implement it:

1) `optional` parameter (like "name")
2) `optional` DSL with lambda that let developer do validation

**Comment by afollestad** [comment]
That's what `isEmptyOr` is for

**Comment by alorma** [comment]
Ok... but no so much clear on my opinion

wouldn't be better to have something like:

```
form {
  input(R.id.input_age, name = "Age", optional = true) {
      ...
  }
}
```

This can wrap it internally with `isEmptyOr`

**Comment by afollestad** [comment]
Your PR changes are in 0.2.0
