### ISSUE TITLE
Implement onErrorCleared event.

### ISSUE THREAD

**Issue by guger** [afollestad/vvalidator#12]
**Description what you'd like to happen:**

I'm using TextInputLayouts to display the errors of the TextInputEditText.
In order to clear the error displayed in the TextInputLayout I need to get notified by the library that the error is resolved.

**Comment by AbdElraoufSabri** [comment]
again for the meanwhile, you've to do it manually.
1. activate real-time validation
2. see this #10

**Comment by afollestad** [comment]
This isn't necessary. When errors are cleared the `onErrors` callback is invoked with an empty list. `TextInputLayout`'s default implementation clears its `error` field when this happens.

**Comment by afollestad** [comment]
https://github.com/afollestad/vvalidator/blob/master/library/src/main/java/com/afollestad/vvalidator/field/input/InputLayoutField.kt#L48-L51

https://github.com/afollestad/vvalidator/blob/master/library/src/main/java/com/afollestad/vvalidator/field/FormField.kt#L147-L157
