### ISSUE TITLE
Setting multiple assertions on the length() property applies only the last one

### ISSUE THREAD

**Issue by ptrbrynt** [afollestad/vvalidator#5]
**Library Version:**

0.4.1
 
**Affected Device(s):**
 
Google Pixel 2 XL with Android Q Beta
 
**Describe the Bug:**

When making assertions on an `EditText` such as:

```kotlin
input(my_edit_text) {
    length().atLeast(4).atMost(5)
}
```

Only the last assertion is applied. Only the following will actually apply all the assertions.

```kotlin
input(my_edit_text) {
    length().atLeast(4)
    length().atMost(5)
}
```

**Expected Behavior:**

Either the chained assertions should work, or some kind of error should be provided when assertions are chained.

**Comment by afollestad** [comment]
@ptrbrynt that actually shouldn't be the case. This is part of the source of `NumberAssertion` which is applied to `EditText`:

```kotlin
override fun isValid(view: EditText): Boolean {
      val intValue = view.text().toIntOrNull() ?: return false
      return when {
        exactly != null && intValue != exactly!! -> false
        lessThan != null && intValue >= lessThan!! -> false
        atMost != null && intValue > atMost!! -> false
        atLeast != null && intValue < atLeast!! -> false
        greaterThan != null && intValue <= greaterThan!! -> false
        else -> true
      }
    }
```

Each chained call after `length()` populates a respective field that all get used in the validation.

**Comment by afollestad** [comment]
@ptrbrynt that actually shouldn't be the case. This is part of the source of `LengthAssertion` which is applied to `EditText`:

```kotlin
override fun isValid(view: EditText): Boolean {
  val length = view.text()
      .length
  return when {
    exactly != null -> length == exactly!!
    lessThan != null -> length < lessThan!!
    atMost != null -> length <= atMost!!
    atLeast != null -> length >= atLeast!!
    greaterThan != null -> length > greaterThan!!
    else -> false
  }
}
```

Each chained call after `length()` populates a respective field that all get used in the validation.

**Comment by afollestad** [comment]
Oh, but it returns early. That is problematic. Will make some changes.

**Comment by ptrbrynt** [comment]
@afollestad Amazing - thanks so much for the quick fix!
