### ISSUE TITLE
About the range of number in NumberAssertion

### ISSUE THREAD

**Issue by cooppor** [afollestad/vvalidator#7]
First of all, thanks for this marvelous library.

After you merged my NumberDecimalAssertion PR,  it became more useful for me, and all 
android project of mine turned to this.  

During this process, I found there may have a little problem with NumberAssertion. When I was using function `isNumber()` to assert a mobile phone number input. This input is number type  and user will typing a phone number which is a 11-length real number and start always with 1, e.g. 13812345678.

But,  in NumberAssertion the number type is Int,  so I think you should consider those situations.

**Comment by afollestad** [comment]
Even though that may solve your use case, you may want to consider a custom assertion for phone numbers, since there isn't real a min/max for phone numbers (but more so formatting rules).

**Comment by cooppor** [comment]
Yes,  I admit it' not a good solution, and finally I solved by using  the `matches ` function.  Thanks anyway.
